server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bullscows
    username: postgres
    password: 1234
  security:
    user:
      name: test
      password: 1234


mybatis:
  mapper-locations:
  - /mappers/*.xml